FROM python:3.11

ARG S3_ENDPOINT
ENV S3_ENDPOINT=${S3_ENDPOINT}
ARG S3_ACCESS_KEY_ID
ENV S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
ARG S3_SECRET_ACCESS_KEY
ENV S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
ARG BUCKET_NAME
ENV BUCKET_NAME=${BUCKET_NAME}

WORKDIR /example

COPY requirements.txt /example/
RUN pip install -r requirements.txt

COPY example /example
COPY data /example/data
